### ISSUE TITLE
ⓘ Notice: Predefined Registry Hives

### ISSUE THREAD

**Issue by BoQsc** [giladreich/RegistryEditor#1]
## ![123044609-90d78a80-d402-11eb-862a-fb24106e205e](https://user-images.githubusercontent.com/21064622/123044738-bc5a7500-d402-11eb-9dcb-c1135b9e3b9a.png) Notice Issue
I've noticed that this like any other resource on the internet predefines Registry Hives.
It's not good or bad thing, I'm simply researching if Windows is keeping track of the Hive names 
and if it is possible to list registry Hives without Predefining.
I'd like to see the original RegistryEditor's Source code, but I believe even there the Predefined Registry Hives are existing.
https://github.com/giladreich/RegistryEditor/blob/5ae7cc233366256cab629b42a42ba52c2ba7eebb/src/Windows.RegistryEditor/Utils/RegistryUtils.cs#L10-L20

## Update:
In the Leaked **Windows XP (NT5)**, the original regedit seems to predefine Registry Hives as well.
A comment to look for in the leaked Windows XP source code
`//  Association between the ASCII name and the handle of the registry key.`
**To be found in a file `regedit/regport.c` such as** `XPSP1/NT/base/fs/utils/regedit/regporte.c` and other files in the source code of Windows XP NT5

### Update2: This issue is just a notice of a deeper issue with the Windows Operating system itself.
Since the issue seems to be permanent among Windows Operating systems, 
I think this issue should be kept open as a notice since it is not resolved and might not be.

**Comment by giladreich** [comment]
Hi @BoQsc,

> It's not good or bad thing

Why? They're pretty much constants and also hardcoded in the .NET core or any library that works with Windows registries.

> I'm simply researching if Windows is keeping track of the Hive names and if it is possible to list registry Hives without Predefining.

Sure thing, you can use [strings][1] on the `regedit.exe` file:
```sh
 λ ./strings64.exe /C/Windows/regedit.exe | grep -E "HK(CR|CU|LM|U|CC)|HKEY" | sort
HKCR
HKCR,".reg"
HKCR,".reg",,,"regfile"
HKCR,"regedit"
HKCR,"regedit",,,"%DESC_RegFile%"
HKCR,"regedit\shell\open\command",,,"regedit.exe %1"
HKCR,"regfile"
HKCR,"regfile","FriendlyTypeName",,"@regedit.exe,-309" ; IDS_FILETYPE
HKCR,"regfile",,,"%DESC_RegFile%"
HKCR,"regfile\DefaultIcon",,,"regedit.exe,1"
HKCR,"regfile\shell\open","MUIVerb",,"@regedit.exe,-310" ; IDS_MERGE
HKCR,"regfile\shell\open",,,"Mer&ge"
HKCR,"regfile\shell\open\command",,,"regedit.exe ""%1"""
HKCU
HKEY_CLASSES_ROOT
HKEY_CURRENT_CONFIG
HKEY_CURRENT_USER
HKEY_LOCAL_MACHINE
HKEY_USERS
HKLM
HKU
```

> I'd like to see the original RegistryEditor's Source code, but I believe even there the Predefined Registry Hives are existing.

Looks like it based on the output above, so you guessed well. :)

To help your research better, lookup for tools to decompile the code, then you can see pretty much how these strings are being referenced in code, e.g. Ghidra, Radare2 (or Cutter for the GUI), IDA Pro, Binary Ninja, Hopper etc...

Hope this helps.


[1]:https://docs.microsoft.com/en-us/sysinternals/downloads/strings

**Comment by BoQsc** [comment]
> Why? They're pretty much constants and also hardcoded in the .NET core or any library that works with Windows registries.

Well I'm just happy that at least we have a standard way, that is widely used. 
By the way, this one is really helpful to know.

> Sure thing, you can use strings on the regedit.exe file:
>  Then you can see pretty much how these strings are being referenced in code

Ahh I'm more simple, I just look up the leaked source code that I find. 

> To help your research better, lookup for tools to decompile the code, then you can see pretty much how these strings are being referenced in code, e.g. Ghidra, Radare2 (or Cutter for the GUI), IDA Pro, Binary Ninja, Hopper etc...

Thanks, your input and your project has motivated me to continue being interested in 
how the things work. :heart:

**Comment by giladreich** [comment]
Thank you for the kind words! Glad to help. :)
